language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - nightly
  - 7.0

before_install:
  composer self-update

install:
  composer install

script:
  php ./vendor/bin/phing test

after_script:
  php ./vendor/bin/test-reporter --coverage-report=build/reports/phpunit-coverage-clover.xml